### ISSUE TITLE
Several algorithms not mentioned on the front page of docs

### ISSUE THREAD

**Issue by tonyelewis** [boostorg/algorithm#55]
Several algorithms provided by the library aren't mentioned on the front page of the docs and hence are likely to go unnoticed by many users.

I'm happy to submit a PR for this. Please shout if I should do that.

**Comment by tonyelewis** [comment]
Some examples:
* `is_increasing(...)`
* `is_strictly_increasing(...)`
* `is_decreasing(...)`
* `is_strictly_decreasing(...)`

**Comment by mclow** [comment]
I'm happy to review a PR for improving the docs.

**Comment by tonyelewis** [comment]
Thanks. I hope to be able to look at this tomorrow.

**Comment by tonyelewis** [comment]
There are 2 steps for me to complete.

Step 2 is for me to actually update the `.qbk` files and check the resulting. This looks substantially less intuitive than I'd anticipated&hellip;:confused:&hellip;

In the meantime, here's the progress I've made re Step 1&hellip;: identifying what I want to add&hellip;

## C++11 Algorithms

* `partition_copy`              &rarr; `boost/algorithm/cxx11/partition_copy.hpp`
* `copy_if`                     &rarr; `boost/algorithm/cxx11/copy_if.hpp`
* `copy_n`                      &rarr; `boost/algorithm/cxx11/copy_n.hpp`
* `iota`                        &rarr; `boost/algorithm/cxx11/iota.hpp`

## C++17 Algorithms

* `for_each_n`                  &rarr; `boost/algorithm/cxx17/for_each_n.hpp`

## Other Algorithms

* `none_of_equal`               &rarr; `none_of.qbk`
* `one_of_equal`                &rarr; `one_of.qbk`
* `is_decreasing`               &rarr; `ordered-hpp.qbk`
* `is_increasing`               &rarr; `ordered-hpp.qbk`
* `is_strictly_decreasing`      &rarr; `ordered-hpp.qbk`
* `is_strictly_increasing`      &rarr; `ordered-hpp.qbk`
* <sub><sup>(`clamp`)</sup></sub>
* `clamp_range`                 &rarr; `clamp-hpp.qbk`
* <sub><sup>(`find_not`)</sup></sub>
* <sub><sup>(`find_backward`)</sup></sub>
* `find_not_backward`           &rarr; `find_backward.qbk`
* `find_if_backward`            &rarr; `find_backward.qbk`
* `find_if_not`                 &rarr; `find_not.qbk`
* `find_if_not_backward`        &rarr; `find_backward.qbk`
* <sub><sup>(`gather`)</sup></sub>
* <sub><sup>(`hex`)</sup></sub>
* `unhex`                       &rarr; `hex.qbk`
* `hex_lower`                   &rarr; `boost/algorithm/hex.hpp`
* <sub><sup>(`is_palindrome`)</sup></sub>
* <sub><sup>(`is_partitioned_until`)</sup></sub>
* <sub><sup>(`apply_permutation`)</sup></sub>
* `apply_reverse_permutation`   &rarr; `apply_permutation.qbk`
* `copy_until`                  &rarr; `boost/algorithm/cxx11/copy_if.hpp`
* `copy_while`                  &rarr; `boost/algorithm/cxx11/copy_if.hpp`
* `iota_n`                      &rarr; `boost/algorithm/cxx11/iota.hpp`
* `power`                       &rarr; `boost/algorithm/algorithm.hpp`

## Not-yet-documented C++17 Algorithms

* `exclusive_scan`              in `boost/algorithm/cxx17/exclusive_scan.hpp`
* `inclusive_scan`              in `boost/algorithm/cxx17/inclusive_scan.hpp`
* `reduce`                      in `boost/algorithm/cxx17/reduce.hpp`
* `transform_exclusive_scan`    in `boost/algorithm/cxx17/transform_exclusive_scan.hpp`
* `transform_inclusive_scan`    in `boost/algorithm/cxx17/transform_inclusive_scan.hpp`
* `transform_reduce`            in `boost/algorithm/cxx17/transform_reduce.hpp`

## Not-yet-documented Other Algorithms

* `minmax`                      in `boost/algorithm/minmax.hpp`
* `first_max_element`           in `boost/algorithm/minmax_element.hpp`
* `first_min_element`           in `boost/algorithm/minmax_element.hpp`
* `first_min_first_max_element` in `boost/algorithm/minmax_element.hpp`
* `first_min_last_max_element`  in `boost/algorithm/minmax_element.hpp`
* `last_max_element`            in `boost/algorithm/minmax_element.hpp`
* `last_min_element`            in `boost/algorithm/minmax_element.hpp`
* `last_min_first_max_element`  in `boost/algorithm/minmax_element.hpp`
* `last_min_last_max_element`   in `boost/algorithm/minmax_element.hpp`
* `minmax_element`              in `boost/algorithm/minmax_element.hpp`
* `partition_subrange`          in `boost/algorithm/sort_subrange.hpp`
* `sort_subrange`               in `boost/algorithm/sort_subrange.hpp`

**Comment by mclow** [comment]
Is this fixed now?

**Comment by tonyelewis** [comment]
Yep - thanks very much. I hope this helps more users get exposed to more of this library.

I'm happy for you to close this issue.
