### ISSUE TITLE
search example should be updated

### ISSUE THREAD

**Issue by pointertoeric** [boostorg/algorithm#64]
all search examples in https://github.com/boostorg/algorithm/blob/develop/example/search_example.cpp 
should be updated with
`ba::boyer_moore_search ( haystack.begin (), haystack.end (), needle1.begin (), needle1.end ()) != std::make_pair(haystack.end(), haystack.end())` instead of `haystack.end()` alone.

**Comment by mclow** [comment]
Updated on develop in 9093abb

**Comment by mclow** [comment]
Merged to release.
