### ISSUE TITLE
Lack of bidimensional for_each

### ISSUE THREAD

**Issue by allopislozano** [boostorg/algorithm#66]
I think it would be nice to have a way to easily apply a binary operation to two zipped ranges (or maybe a Nary operation to n zipped ranges).  
It would be kind of  boost::accumulate but returning void and that would not accumulate along the container dimension.
Example:
https://godbolt.org/z/gWFvcn

**Comment by mclow** [comment]
Wouldn't the existing `for_each` work for a zipped range (using `ranges3`)?
The operation would have to be unary - but it would take a tuple of values.

**Comment by mclow** [comment]
Or using `boost::range` :-)

**Comment by allopislozano** [comment]
Hi Marshall, thank you for your answer, indeed I think that's the best solution, hadn't though about that possibility: https://godbolt.org/z/VXk6cs

by the way, I really like your talks on youtube :)
