### ISSUE TITLE
The apply_permutation algorithm requires C++11

### ISSUE THREAD

**Issue by eldiener** [boostorg/algorithm#78]
The apply_permutation algorithm requires C++11. Is this intended ? 

If so, should the apply_permutation test only run when the compiler is at the C++11 or higher level ?
If not so, should apply_permutation be changed to use Boost type traits rather than standard type traits, and will it work that way ?

**Comment by mclow** [comment]
As far as I know, this has not ben true since October 2018. (commit b6c04d6dc52ace864bb1f5cd26b65f9b639a39b9)

**Comment by eldiener** [comment]
See https://github.com/boostorg/algorithm/pull/82.

**Comment by ksoni-1258** [comment]
what is the issue,could you please elaborate

**Comment by eldiener** [comment]
It has been fixed. The issue is that the header file included <type_traits>, which is a C++11 header file.
