### ISSUE TITLE
Any plan for C++20 container related algorithms such as std::erase(_if)?

### ISSUE THREAD

**Issue by nanoric** [boostorg/algorithm#89]
In the past, since boost is a much larger and much heavier library, using boost is always more convience than using pure STL.
But with new standards comes, STL has its own std::erase_if or something else (better range support etc.) for different STL containers.
As a result, using boost containers is not as convient as expected. Especially when STL and boost are mixed.
So is here any plan to update boost's algorithm library/container library for a better exprience?

**Comment by mclow** [comment]
Yes; there are plans for the coming year.
